# Generated by Django 4.0.4 on 2022-06-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0004_auto_20211027_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Messengers',
                'verbose_name_plural': '2. Videos',
            },
        ),
        migrations.DeleteModel(
            name='FaqModel',
        ),
        migrations.DeleteModel(
            name='PriceListModel',
        ),
        migrations.DeleteModel(
            name='SerificateModel',
        ),
        migrations.AlterModelOptions(
            name='photomodel',
            options={'verbose_name': 'Photo', 'verbose_name_plural': '2.Photo'},
        ),
        migrations.AlterModelOptions(
            name='videomodel',
            options={'verbose_name': 'Video', 'verbose_name_plural': '3. Videos'},
        ),
        migrations.AddField(
            model_name='about',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description Uz'),
        ),
        migrations.AddField(
            model_name='photomodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description UZ'),
        ),
        migrations.AddField(
            model_name='videomodel',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description UZ'),
        ),
    ]
