# Generated by Django 4.0.4 on 2022-06-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0005_messenger_delete_faqmodel_delete_pricelistmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messenger',
            options={'verbose_name': 'Messengers', 'verbose_name_plural': '2. Messengers'},
        ),
    ]
