# Generated by Django 4.0.4 on 2022-06-09 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_product_category_name_uz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('longitude', models.CharField(max_length=400, verbose_name='Longitude')),
                ('latitude', models.CharField(max_length=400, verbose_name='Latitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.user', verbose_name='User')),
            ],
        ),
    ]
