# Generated by Django 4.0.4 on 2022-06-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.AddField(
            model_name='location',
            name='user_id',
            field=models.CharField(max_length=400, null=True, verbose_name='User id'),
        ),
    ]
