# Generated by Django 4.0.4 on 2022-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_location_user_location_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=400, null=True, verbose_name='User id')),
                ('begin_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Cashback',
                'verbose_name_plural': '5.Cashbacks',
            },
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': '5.Locations'},
        ),
    ]
