# Generated by Django 4.0.4 on 2022-06-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_cashback_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': 'Cashback', 'verbose_name_plural': '7.Cashbacks'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': '6.Locations'},
        ),
    ]
