# Generated by Django 4.0.4 on 2022-06-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_order_aksiya_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='aksiya',
        ),
        migrations.AddField(
            model_name='product',
            name='aksiya',
            field=models.BooleanField(default=False),
        ),
    ]
