# Generated by Django 4.0.4 on 2022-06-14 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_order_aksiya_product_aksiya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='aksiya',
        ),
        migrations.CreateModel(
            name='ProductAksiya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Product name En')),
                ('name_ru', models.CharField(default='S', max_length=200, verbose_name='Product name Ru')),
                ('name_uz', models.CharField(default='S', max_length=200, verbose_name='Product name Uz')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Price')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description Ru')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description En')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description Uz')),
                ('photo', models.CharField(max_length=1000, verbose_name='Photo')),
                ('begin_aksiya', models.IntegerField(default=0, verbose_name='Begin akysiya')),
                ('count_a', models.IntegerField(default=0, verbose_name='Count akysiya')),
                ('category_name_ru', models.CharField(blank=True, max_length=300, null=True, verbose_name='Category Ru')),
                ('category_name_uz', models.CharField(blank=True, max_length=300, null=True, verbose_name='Category Ru')),
                ('category_code', models.CharField(blank=True, max_length=300, verbose_name='Unnecassary category-code')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcategory', verbose_name='Category En')),
            ],
            options={
                'verbose_name': 'Product Aktsiya',
                'verbose_name_plural': '3.Products Aktsiya',
            },
        ),
    ]
