# Generated by Django 4.0.4 on 2022-06-15 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_remove_product_aksiya_productaksiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='productA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productaksiya', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Product'),
        ),
    ]
