# Generated by Django 4.0.5 on 2022-06-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_product_aksiya_productaksiya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartmodel',
            options={'verbose_name': 'Cart', 'verbose_name_plural': '5.Carts'},
        ),
        migrations.AlterModelOptions(
            name='cashback',
            options={'verbose_name': 'Cashback', 'verbose_name_plural': '8.Cashbacks'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': '7.Locations'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': '6.Orders'},
        ),
        migrations.AlterModelOptions(
            name='productaksiya',
            options={'verbose_name': 'Product Aktsiya', 'verbose_name_plural': '4.Products Aktsiya'},
        ),
    ]
