# Generated by Django 4.0.5 on 2022-06-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_cartmodel_options_alter_cashback_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productaksiya',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
    ]
