# Generated by Django 4.0.5 on 2022-07-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_productaksiya_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Category Image'),
        ),
    ]
